// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFqSov9R5k6U_rERbM_cR3lvm_yhjjz4',
    appId: '1:917081303248:web:aaeb258477f7b56a4156d5',
    messagingSenderId: '917081303248',
    projectId: 'cpsrpo',
    authDomain: 'cpsrpo.firebaseapp.com',
    storageBucket: 'cpsrpo.firebasestorage.app',
    measurementId: 'G-VP6K6PH0Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeoXz1rYg2ASueSpN9S6MKP6cnUChj6SY',
    appId: '1:917081303248:android:cec34d746c87e6c04156d5',
    messagingSenderId: '917081303248',
    projectId: 'cpsrpo',
    storageBucket: 'cpsrpo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJgJp_bzwzwtXqZ5grB7Zl4Rn3YfGSK3A',
    appId: '1:917081303248:ios:93a51216b52dcba84156d5',
    messagingSenderId: '917081303248',
    projectId: 'cpsrpo',
    storageBucket: 'cpsrpo.firebasestorage.app',
    iosBundleId: 'com.example.cpsrpoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJgJp_bzwzwtXqZ5grB7Zl4Rn3YfGSK3A',
    appId: '1:917081303248:ios:93a51216b52dcba84156d5',
    messagingSenderId: '917081303248',
    projectId: 'cpsrpo',
    storageBucket: 'cpsrpo.firebasestorage.app',
    iosBundleId: 'com.example.cpsrpoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChFqSov9R5k6U_rERbM_cR3lvm_yhjjz4',
    appId: '1:917081303248:web:e875ffad92063d564156d5',
    messagingSenderId: '917081303248',
    projectId: 'cpsrpo',
    authDomain: 'cpsrpo.firebaseapp.com',
    storageBucket: 'cpsrpo.firebasestorage.app',
    measurementId: 'G-C16Z7SRYFK',
  );
}
